const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ux=require('../scripts/core-ux-contract.js');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const window={start:'2026-10-01',end:'2026-10-07'};
const metrics=['weight','fatMass','sleepHours','trainingSets','caloriesBurned','caloriesIntake','steps','spo2'];
function fn(name){const start=html.indexOf(`    function ${name}(`);assert.ok(start>=0);return html.slice(start,html.indexOf('\n    function ',start+1));}
for(const [days,startDate] of [[7,'2026-10-01'],[30,'2026-09-08'],[90,'2026-07-10']]){
  test(`${days} inclusive Taipei calendar days end on October 7`,()=>{const range=ux.getCalendarDateRange(days,'Asia/Taipei','2026-10-07T23:59:59+08:00');assert.deepEqual(range,{startDate,endDate:'2026-10-07',days});assert.equal(ux.localDateRange(range.startDate,range.endDate).length,days);});
  test(`${days} API params use explicit dates and preserve empty days`,()=>{const calls=[],context=vm.createContext({HealthCoreUX:ux,CONFIG:{TIMEZONE:'Asia/Taipei'},getLocalDateString:()=> '2026-10-07',PERF_DEBUG:false,apiGet:(action,payload)=>calls.push({action,payload})});vm.runInContext(fn('resolveDateRange'),context);const range=context.resolveDateRange(`${days}d`);const method=html.match(/getHealthTimeline:\(start,end\)=>apiGet\("getHealthTimeline",[^\n]+/)[0].replace(/,$/,'');vm.runInContext(`globalThis.api={${method}}`,context);context.api.getHealthTimeline(range.startDate,range.endDate);assert.deepEqual(JSON.parse(JSON.stringify(calls)),[{action:'getHealthTimeline',payload:{startDate,endDate:'2026-10-07'}}]);assert.equal(ux.dailyMetricBuckets([],{start:startDate,end:'2026-10-07'}).length,days);});
}
test('timestamp first resolves to Taipei date at the UTC midnight boundary',()=>{assert.equal(ux.getCalendarDateRange(7,'Asia/Taipei','2026-10-06T15:59:59Z').endDate,'2026-10-06');assert.deepEqual(ux.getCalendarDateRange(7,'Asia/Taipei','2026-10-06T16:00:00Z'),{startDate:'2026-10-01',endDate:'2026-10-07',days:7});assert.equal(ux.getCalendarDateRange(7,'Asia/Taipei','2026-10-07T00:01:00Z').endDate,'2026-10-07');});
test('calendar helper crosses month, year and leap boundaries',()=>{assert.equal(ux.getCalendarDateRange(7,'Asia/Taipei','2026-01-03').startDate,'2025-12-28');assert.equal(ux.getCalendarDateRange(7,'Asia/Taipei','2024-03-02').startDate,'2024-02-25');assert.equal(ux.localDateRange('2024-02-25','2024-03-02').length,7);});
for(const metric of metrics){
  test(`${metric}: three observations occupy three real calendar positions and four NULLs`,()=>{const input=[{date:'2026-10-01',[metric]:82.1},{date:'2026-10-03',[metric]:81.8},{date:'2026-10-06',[metric]:81.5}],copy=JSON.stringify(input),rows=ux.dailyMetricBuckets(input,window);assert.deepEqual(rows.map(r=>r[metric]),[82.1,null,81.8,null,null,81.5,null]);assert.equal(rows[0].date,window.start);assert.equal(rows.at(-1).date,window.end);assert.deepEqual(ux.latestRangeMetric(rows,metric,window),{date:'2026-10-06',value:81.5});assert.equal(JSON.stringify(input),copy);assert.equal(ux.linearTrend(rows.map(r=>r[metric])).endIndex,5);});
}
test('seven full days include observed zero but never synthesize missing zero',()=>{const input=ux.localDateRange(window.start,window.end).map((date,i)=>({date,trainingSets:i}));assert.deepEqual(ux.dailyMetricBuckets(input,window).map(r=>r.trainingSets),[0,1,2,3,4,5,6]);assert.ok(ux.dailyMetricBuckets([],window).every(r=>r.trainingSets===null));});
test('latest seven records are not a seven-day window; old/future values cannot leak in',()=>{const input=Array.from({length:7},(_,i)=>({date:ux.shiftLocalDate('2026-09-30',-i*10),weight:80+i})).concat([{date:'2026-10-08',weight:1}]);const rows=ux.dailyMetricBuckets(input,window);assert.equal(rows.length,7);assert.ok(rows.every(r=>r.weight===null));assert.equal(ux.latestRangeMetric(input,'weight',window),null);assert.equal(ux.linearTrend(rows.map(r=>r.weight)),null);});
test('range summary remains latest real value when the single-day cursor moves',()=>{const rows=ux.dailyMetricBuckets([{date:'2026-10-06',weight:81.5}],window),context=vm.createContext({HealthCoreUX:ux,rows,metricConfig:()=>({label:'體重',color:'#000'}),metricDisplay:(_,v)=>v===null?'—':String(v),escapeHtml:String,shortDateLabel:String,longDateLabel:String});for(const name of ['valid','num','metricRange','sharedSegments','renderSharedPanel'])vm.runInContext(fn(name),context);const output=context.renderSharedPanel('weight',rows,0);assert.match(output,/<b>81.5<\/b>/);assert.match(output,/2026-10-06 · 期間最新紀錄/);assert.match(output,/aria-valuetext="2026-10-01，體重 —"/);assert.doesNotMatch(output,/所選日期尚無紀錄|class="shared-trendline"/);});
test('empty range says seven days without records while keeping complete axis',()=>{const target={},axis={},context=vm.createContext({HealthCoreUX:ux,CONFIG:{TIMEZONE:'Asia/Taipei'},appState:{healthTimeline:[{date:'2026-09-29',weight:99}]},sectionWindows:{body:window},selectedHealthDate:null,sharedTrendMetrics:['weight','fatMass','sleepHours','trainingSets','caloriesBurned'],sharedTrendRenderKey:'',document:{getElementById:id=>id==='shared-health-trends'?target:axis,documentElement:{dataset:{theme:'dark'}}},metricConfig:m=>({label:m,color:'#000'}),metricDisplay:(_,v)=>v===null?'—':String(v),escapeHtml:String,shortDateLabel:String,longDateLabel:String,renderDailyDetail:()=>{},bindSharedTrendInteraction:()=>{}});for(const name of ['valid','num','metricRange','sharedSegments','sharedTimelineRows','renderSharedPanel','renderSharedHealthTrends'])vm.runInContext(fn(name),context);context.renderSharedHealthTrends(true);assert.equal(context.sharedTimelineRows().length,7);assert.match(axis.innerHTML,/2026-10-01/);assert.match(axis.innerHTML,/2026-10-07/);assert.equal((target.innerHTML.match(/<small>7 天內無紀錄<\/small>/g)||[]).length,5);assert.doesNotMatch(target.innerHTML,/99|所選日期尚無紀錄/);});
test('date cursor navigation uses the full calendar bucket index',()=>{const context=vm.createContext({HealthCoreUX:ux,CONFIG:{TIMEZONE:'Asia/Taipei'},appState:{healthTimeline:[{date:'2026-10-06',weight:81.5}]},sectionWindows:{body:window},selectedHealthDate:null,renderSharedHealthTrends:()=>{}});for(const name of ['sharedTimelineRows','selectedTimelineRow','selectHealthDate'])vm.runInContext(fn(name),context);context.selectHealthDate(1);assert.equal(context.selectedHealthDate,'2026-10-02');assert.equal(context.selectedTimelineRow().weight,null);context.selectHealthDate(5);assert.equal(context.selectedTimelineRow().weight,81.5);});
