const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ui=require('../scripts/training-personal-web.js');
const source=fs.readFileSync(require.resolve('../scripts/training-personal-web.js'),'utf8');
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
function harness(){
 const nodes=new Map(),calls=[];
 const element=id=>{if(!nodes.has(id))nodes.set(id,{id,hidden:id==='training-personal-panel',dataset:{},value:id==='training-personal-range'?'all':id==='training-personal-exercise'?'bench':'',textContent:'',innerHTML:'',replaceChildren(){this.innerHTML='';this.textContent='';},append(){},scrollIntoView(){},reset(){},reportValidity(){return true;},setCustomValidity(){}});return nodes.get(id);};
 const document={getElementById:element,addEventListener(){},createElement:()=>({})};
 const context=vm.createContext({document,Intl,Promise,Set,Map,Number,String,Date,console,currentUser:'A',localSessionEpoch:1,crypto:require('node:crypto').webcrypto,getLocalDateString:()=> '2026-10-09',readableError:e=>e.message,localEngineRequest:(action,payload)=>{const d=deferred();calls.push({action,payload,...d});return d.promise;}});
 vm.runInContext(source,context);context.TrainingPersonal.init();
 return {context,calls,element,finish:async(index,data)=>{calls[index].resolve(data);await new Promise(resolve=>setImmediate(resolve));}};
}
const catalog=[{exerciseId:'bench',exerciseName:'Bench'}];
const pr={range:{startDate:null,endDate:'2026-10-09'},groups:[],excluded:[]};
test('no qualifier stays NULL with no invented zero percent',()=>{const view=ui.goalView({status:'IN_PROGRESS',qualifiedBest:null,achievementPercent:null,progressBarPercent:null,remainingLoadKg:null});assert.equal(view.bar,null);assert.equal(view.percent,'尚無符合次數條件的紀錄');assert.equal(view.remaining,'—');});
test('overachievement preserves actual performance while progress bar remains capped',()=>{const view=ui.goalView({status:'ACHIEVED',qualifiedBest:{load:150,unit:'kg',reps:6,date:'2026-10-07'},achievementPercent:107.14,progressBarPercent:100,remainingLoadKg:0});assert.equal(view.bar,100);assert.match(view.best,/150 kg × 6/);assert.equal(view.percent,'107.14%');});
test('goal bases omit unknown/bodyweight/assistance, record form preserves unknown option',()=>{assert.doesNotMatch(ui.basisOptions('',true),/UNKNOWN|BODYWEIGHT|ASSISTANCE/);assert.match(ui.basisOptions(),/UNKNOWN.* selected/);});
test('PR read uses selected exercise and independent all-time/7-day contract',async()=>{const h=harness();h.element('open-personal-records').onclick();await h.finish(0,catalog);assert.equal(h.calls[1].action,'getTrainingPersonalRecords');assert.equal(h.calls[1].payload.days,'all');await h.finish(1,pr);h.element('training-personal-range').value='7';h.element('training-personal-range').onchange();assert.equal(h.calls[2].payload.days,'7');await h.finish(2,{...pr,range:{startDate:'2026-10-03',endDate:'2026-10-09'}});assert.match(h.element('training-personal-content').innerHTML,/2026-10-03 ～ 2026-10-09/);});
test('goal read has no dashboard or PR range params',async()=>{const h=harness();h.element('open-training-goals').onclick();await h.finish(0,catalog);assert.equal(h.calls[1].action,'getTrainingGoals');assert.equal(h.calls[1].payload,undefined);await h.finish(1,{goals:[]});assert.match(h.element('training-personal-content').innerHTML,/尚未設定訓練目標/);});
test('failed read is an error state, not an empty training result',async()=>{const h=harness();h.element('open-personal-records').onclick();await h.finish(0,catalog);h.calls[1].reject(Error('SQL_UNAVAILABLE'));await new Promise(resolve=>setImmediate(resolve));assert.equal(h.element('training-personal-content').dataset.state,'error');assert.match(h.element('training-personal-content').textContent,/讀取失敗/);});
test('late response from a prior selection cannot overwrite the current selection',async()=>{const h=harness();h.element('open-personal-records').onclick();await h.finish(0,catalog);h.element('training-personal-range').value='7';h.element('training-personal-range').onchange();await h.finish(2,{...pr,range:{startDate:'2026-10-03',endDate:'2026-10-09'}});const current=h.element('training-personal-content').innerHTML;await h.finish(1,pr);assert.equal(h.element('training-personal-content').innerHTML,current);});
test('logout resets private DOM and an old account response cannot restore it',async()=>{const h=harness();h.element('open-personal-records').onclick();await h.finish(0,catalog);h.context.currentUser='B';h.context.localSessionEpoch++;h.context.TrainingPersonal.reset();await h.finish(1,pr);assert.equal(h.element('training-personal-content').innerHTML,'');assert.equal(h.element('training-personal-panel').hidden,true);});
test('source links carry exact record and revision; display text is escaped',async()=>{const h=harness();h.element('open-personal-records').onclick();await h.finish(0,catalog);const r={recordId:'owned-id',revision:'9',load:50,unit:'kg',reps:8,date:'2026-10-07',ties:[]};await h.finish(1,{...pr,groups:[{exerciseName:'<script>untrusted</script>',comparison:{loadBasis:'BARBELL_TOTAL'},bestByReps:[r],records:[r]}]});const html=h.element('training-personal-content').innerHTML;assert.match(html,/data-pr-record="owned-id" data-pr-revision="9"/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>untrusted/);});
